# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Download nuGet packages
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
   command: restore
   projects: '**/*.csproj'

# Build the project
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
   projects: '**/*.csproj'
   arguments: '--configuration $(buildConfiguration)'   
 
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
   command: publish
   publishWebProjects: false
   projects: '**/*.csproj'
   arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Public Artifact: drop'
  inputs:
   artifactName: 'AzureDemoPipeline' 

